name: adlertestenvironment

services:
  moodle:
    ports:
      - '${_PORT_MOODLE}:8080'
    environment:
      DECLARATIVE_SETUP_MANAGER_PASSWORD: ${_USER_MANAGER_PW}
      DECLARATIVE_SETUP_STUDENT_PASSWORD: ${_USER_STUDENT_PW}
      ADLER_PLAYBOOK_ROLES: "test_users"

  backend:
    ports:
      - '${_PORT_BACKEND}:80'

  frontend:
    ports:
      - '${_PORT_3D}:80'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOSTS: db_moodle,db_backend
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${_DB_ROOT_PW}
    restart: unless-stopped
    depends_on:
      # - db_backend
      - db_moodle
    ports:
      - '8088:80'