services:
  # if needed, add additional services here. It should be possible to just copy and paste them from non-moodle/docker-compose.yml
  # note that not required env variables have been removed, so you might need to add them back in when copying services over.
  db_moodle:
    image: docker.io/bitnami/mariadb:10.11
    ports:
      - "3312:3306"
    environment:
      MARIADB_USER: ${_DB_MOODLE_USER}
      MARIADB_PASSWORD: ${_DB_MOODLE_PW}
      MARIADB_ROOT_PASSWORD: ${_DB_ROOT_PW}
      MARIADB_DATABASE: ${_DB_MOODLE_NAME}
      MARIADB_CHARACTER_SET: utf8mb4
      MARIADB_COLLATE: utf8mb4_unicode_ci
    volumes:
      - db_moodle_data:/bitnami/mariadb
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "/opt/bitnami/scripts/mariadb/healthcheck.sh" ]
      start_period: 10s
      interval: 15s
      timeout: 5s

volumes:
  db_moodle_data:
