services:
  pgsql_db_moodle:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${_DB_MOODLE_USER}
      POSTGRES_PASSWORD: ${_DB_MOODLE_PW}
      POSTGRES_DB: ${_DB_MOODLE_NAME}
    volumes:
      - psql_db_moodle_data:/var/lib/postgresql/data
    restart: unless-stopped

  psgql_adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8079:8080"


volumes:
  psql_db_moodle_data: